// Code generated by "stringer -linecomment -type=cudEvent internal/service/raiting/metrics.go"; DO NOT EDIT.

package raiting

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CUDEventCreate-1]
	_ = x[CUDEventUpdate-2]
	_ = x[CUDEventDelete-3]
}

const _cudEvent_name = "createupdatedelete"

var _cudEvent_index = [...]uint8{0, 6, 12, 18}

func (i cudEvent) String() string {
	i -= 1
	if i >= cudEvent(len(_cudEvent_index)-1) {
		return "cudEvent(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _cudEvent_name[_cudEvent_index[i]:_cudEvent_index[i+1]]
}
